### ISSUE TITLE
GitHub Pages

### ISSUE THREAD

**Issue by Rudxain** [p2js/shaditor#1]
I recommend this repo to be converted into a GH Pages Site. It's easy, and doesn't require modifying the source files. I can help you with the setup.

I recommend it because it allows easier access from any device and OS (as long as it has a browser). It also allows support of new features that CORS would reject on `file:///` URI schemes, like ESM module files, some HTTP requests, and the `crypto` API.

The code will still work offline and be client-side, but it'll be served by GH every time someone clicks the link (and will also be cached by the User Agent)

**Comment by p2js** [comment]
I'm gonna get around to writing a proper readme.md in a couple of days' time, but I'm already hosting this little editor on my personal website, https://alfiot.net/shaditor. I think it would be a little redundant to have the github page up for this, but if there are benefits i could get around to it.

**Comment by Rudxain** [comment]
I agree. If you already host it on a website then there's no need for GHP. In that case I recommend you to edit the "about settings" (not the repo settings, I mean the dialog box with the title "Edit repository details"). You can add tags for better SEO, and there's a dedicated text box to fill with a URL link, it will be shown in the "About" section for anyone to click (The link will still be shown in the mobile layout version of GH, they usually hide some buttons but the link isn't hidden)

**Comment by Rudxain** [comment]
And I'm sorry for opening an unnecessary Issue. I didn't know you have a website. I noticed the profile link now
